// <auto-generated />
using System;
using Adambnb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adambnb.Migrations
{
    [DbContext(typeof(AdambnbContext))]
    [Migration("20240624210028_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adambnb.Models.Costumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Costumers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int>("LandLordId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandLordId")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCover = true,
                            LandLordId = 1,
                            LocationId = 1,
                            Url = "https://watismijnhuiswaard.com/wp-content/uploads/2021/06/Boerderij-1024x512.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsCover = true,
                            LandLordId = 2,
                            LocationId = 2,
                            Url = "https://www.egmondverhuur.nl/sites/egmondverhuur/files/styles/slide/public/images/appartementen-met-zeezicht_0.jpg?itok=iAWaBQd2"
                        },
                        new
                        {
                            Id = 3,
                            IsCover = true,
                            LandLordId = 3,
                            LocationId = 6,
                            Url = "https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                        },
                        new
                        {
                            Id = 4,
                            IsCover = true,
                            LandLordId = 4,
                            LocationId = 7,
                            Url = "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=2075&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                        },
                        new
                        {
                            Id = 5,
                            IsCover = true,
                            LandLordId = 5,
                            LocationId = 8,
                            Url = "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                        },
                        new
                        {
                            Id = 6,
                            IsCover = true,
                            LandLordId = 6,
                            LocationId = 9,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-15.jpg"
                        },
                        new
                        {
                            Id = 7,
                            IsCover = true,
                            LandLordId = 7,
                            LocationId = 10,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsCover = true,
                            LandLordId = 8,
                            LocationId = 11,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-13.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsCover = true,
                            LandLordId = 9,
                            LocationId = 12,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-13.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsCover = true,
                            LandLordId = 10,
                            LocationId = 13,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-10.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsCover = true,
                            LandLordId = 11,
                            LocationId = 14,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-19.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsCover = true,
                            LandLordId = 12,
                            LocationId = 15,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-9.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsCover = true,
                            LandLordId = 16,
                            LocationId = 3,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-5.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsCover = true,
                            LandLordId = 17,
                            LocationId = 4,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-10.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsCover = true,
                            LandLordId = 18,
                            LocationId = 5,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-19.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsCover = false,
                            LandLordId = 19,
                            LocationId = 1,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-9.jpg"
                        },
                        new
                        {
                            Id = 20,
                            IsCover = false,
                            LandLordId = 20,
                            LocationId = 2,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-5.jpg"
                        },
                        new
                        {
                            Id = 21,
                            IsCover = false,
                            LandLordId = 21,
                            LocationId = 3,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-10.jpg"
                        },
                        new
                        {
                            Id = 22,
                            IsCover = false,
                            LandLordId = 22,
                            LocationId = 4,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-19.jpg"
                        },
                        new
                        {
                            Id = 23,
                            IsCover = false,
                            LandLordId = 23,
                            LocationId = 5,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-9.jpg"
                        },
                        new
                        {
                            Id = 24,
                            IsCover = false,
                            LandLordId = 24,
                            LocationId = 6,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-5.jpg"
                        },
                        new
                        {
                            Id = 25,
                            IsCover = false,
                            LandLordId = 25,
                            LocationId = 7,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-10.jpg"
                        },
                        new
                        {
                            Id = 26,
                            IsCover = false,
                            LandLordId = 26,
                            LocationId = 8,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-19.jpg"
                        },
                        new
                        {
                            Id = 27,
                            IsCover = false,
                            LandLordId = 27,
                            LocationId = 9,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-9.jpg"
                        },
                        new
                        {
                            Id = 28,
                            IsCover = false,
                            LandLordId = 28,
                            LocationId = 10,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-5.jpg"
                        },
                        new
                        {
                            Id = 29,
                            IsCover = false,
                            LandLordId = 29,
                            LocationId = 11,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-10.jpg"
                        },
                        new
                        {
                            Id = 30,
                            IsCover = false,
                            LandLordId = 30,
                            LocationId = 12,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-19.jpg"
                        },
                        new
                        {
                            Id = 31,
                            IsCover = false,
                            LandLordId = 31,
                            LocationId = 13,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-9.jpg"
                        },
                        new
                        {
                            Id = 32,
                            IsCover = false,
                            LandLordId = 32,
                            LocationId = 14,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-5.jpg"
                        },
                        new
                        {
                            Id = 33,
                            IsCover = false,
                            LandLordId = 33,
                            LocationId = 15,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-10.jpg"
                        },
                        new
                        {
                            Id = 34,
                            IsCover = false,
                            LandLordId = 34,
                            LocationId = 1,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-19.jpg"
                        },
                        new
                        {
                            Id = 35,
                            IsCover = false,
                            LandLordId = 35,
                            LocationId = 2,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-9.jpg"
                        },
                        new
                        {
                            Id = 36,
                            IsCover = false,
                            LandLordId = 36,
                            LocationId = 3,
                            Url = "https://generatorfun.com/code/uploads/Random-House-image-5.jpg"
                        });
                });

            modelBuilder.Entity("Adambnb.Models.LandLord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LandLords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            FirstName = "Landlord1",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 40,
                            FirstName = "Landlord2",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 4,
                            Age = 40,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 5,
                            Age = 45,
                            FirstName = "Adam",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 6,
                            Age = 38,
                            FirstName = "Emily",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 7,
                            Age = 42,
                            FirstName = "Michael",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 8,
                            Age = 37,
                            FirstName = "Sarah",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 9,
                            Age = 39,
                            FirstName = "Robert",
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 10,
                            Age = 41,
                            FirstName = "Laura",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 11,
                            Age = 36,
                            FirstName = "Daniel",
                            LastName = "Robinson"
                        },
                        new
                        {
                            Id = 12,
                            Age = 43,
                            FirstName = "Lisa",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 13,
                            Age = 44,
                            FirstName = "William",
                            LastName = "Hernandez"
                        },
                        new
                        {
                            Id = 14,
                            Age = 33,
                            FirstName = "Patricia",
                            LastName = "Lopez"
                        },
                        new
                        {
                            Id = 15,
                            Age = 39,
                            FirstName = "Richard",
                            LastName = "Lewis"
                        },
                        new
                        {
                            Id = 16,
                            Age = 34,
                            FirstName = "Karen",
                            LastName = "Clark"
                        },
                        new
                        {
                            Id = 17,
                            Age = 32,
                            FirstName = "Jason",
                            LastName = "Young"
                        },
                        new
                        {
                            Id = 18,
                            Age = 20,
                            FirstName = "Adam",
                            LastName = "Lin"
                        },
                        new
                        {
                            Id = 19,
                            Age = 54,
                            FirstName = "Lo",
                            LastName = "La"
                        },
                        new
                        {
                            Id = 20,
                            Age = 22,
                            FirstName = "Tom",
                            LastName = "Voldoende"
                        },
                        new
                        {
                            Id = 21,
                            Age = 34,
                            FirstName = "Rico",
                            LastName = "Sof"
                        },
                        new
                        {
                            Id = 22,
                            Age = 23,
                            FirstName = "Gert",
                            LastName = "Jan"
                        },
                        new
                        {
                            Id = 23,
                            Age = 23,
                            FirstName = "Dit",
                            LastName = "Vak"
                        },
                        new
                        {
                            Id = 24,
                            Age = 23,
                            FirstName = "Is",
                            LastName = "Leuk"
                        },
                        new
                        {
                            Id = 25,
                            Age = 45,
                            FirstName = "Hans",
                            LastName = "Kazan"
                        },
                        new
                        {
                            Id = 26,
                            Age = 54,
                            FirstName = "Mohammed",
                            LastName = "Salah"
                        },
                        new
                        {
                            Id = 27,
                            Age = 65,
                            FirstName = "Han",
                            LastName = "fee"
                        },
                        new
                        {
                            Id = 28,
                            Age = 43,
                            FirstName = "DA",
                            LastName = "effe"
                        },
                        new
                        {
                            Id = 29,
                            Age = 65,
                            FirstName = "da",
                            LastName = "vdfv"
                        },
                        new
                        {
                            Id = 30,
                            Age = 64,
                            FirstName = "dw",
                            LastName = "t4"
                        },
                        new
                        {
                            Id = 31,
                            Age = 34,
                            FirstName = "Jop",
                            LastName = "rt"
                        },
                        new
                        {
                            Id = 32,
                            Age = 32,
                            FirstName = "wceadweas",
                            LastName = "trer"
                        },
                        new
                        {
                            Id = 33,
                            Age = 32,
                            FirstName = "ef",
                            LastName = "gh"
                        },
                        new
                        {
                            Id = 34,
                            Age = 43,
                            FirstName = "feef",
                            LastName = "hdfg"
                        },
                        new
                        {
                            Id = 35,
                            Age = 32,
                            FirstName = "ef",
                            LastName = "gh"
                        },
                        new
                        {
                            Id = 36,
                            Age = 43,
                            FirstName = "feef",
                            LastName = "hdfg"
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LandLordId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandLordId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "De camping ligt verscholen achter de boerderij in de polder. Geniet van de rust en ruimte op De Boerenhoeve, waar de natuur je omringt en de frisse lucht je verwelkomt. Onze comfortabele appartementen bieden een thuis weg van huis, met moderne voorzieningen en een sfeervolle inrichting. Ontspan op het terras en bewonder het prachtige uitzicht op de omringende weilanden. Of verken de nabijgelegen wandel- en fietspaden voor een onvergetelijke ervaring in de natuur. We heten je van harte welkom op De Boerenhoeve!",
                            FeaturesList = "[2,3]",
                            LandLordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 100f,
                            Rooms = 2,
                            Subtitle = "Lekker veel ruimte",
                            Title = "De Boerenhoeve",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ervaar de ultieme vakantie aan de kust in ons Zeezicht Appartement. Geniet van adembenemende uitzichten op de zee vanuit je ruime en comfortabele accommodatie. Ontspan op het balkon en luister naar het rustgevende geluid van de golven. Het appartement is smaakvol ingericht en voorzien van moderne voorzieningen. Verken de nabijgelegen stranden, restaurants en bezienswaardigheden voor een onvergetelijke vakantie aan zee.",
                            FeaturesList = "[2,3,4]",
                            LandLordId = 2,
                            NumberOfGuests = 6,
                            PricePerDay = 150f,
                            Rooms = 3,
                            Subtitle = "Prachtig uitzicht op de zee",
                            Title = "Zeezicht Appartement",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ontsnap aan de drukte en omarm de natuur in ons Groene Oase Chalet. Dit charmante chalet is omgeven door weelderig groen en biedt een rustige toevluchtsoord voor natuurliefhebbers. Het chalet is voorzien van alle gemakken en beschikt over een eigen tuin waar je kunt genieten van de flora en fauna. Verken de wandelpaden, observeer vogels en kom helemaal tot rust in deze groene oase.",
                            FeaturesList = "[1,5]",
                            LandLordId = 1,
                            NumberOfGuests = 2,
                            PricePerDay = 120f,
                            Rooms = 1,
                            Subtitle = "Omgeven door natuur",
                            Title = "Groene Oase Chalet",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Verblijf in stijl in ons Historisch Stadsappartement, gelegen in het hart van de oude stad. Het appartement combineert moderne luxe met historische charme en biedt een unieke ervaring. Wandel door smalle steegjes, ontdek historische bezienswaardigheden en proef lokale gerechten in de nabijgelegen restaurants. Het appartement is smaakvol ingericht en voorzien van alle moderne gemakken voor een comfortabel en cultureel verblijf.",
                            FeaturesList = "[2,3]",
                            LandLordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 130f,
                            Rooms = 2,
                            Subtitle = "Verken de oude stad",
                            Title = "Historisch Stadsappartement",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Escape to this charming cottage nestled by the serene lake. Enjoy the rustic charm and peaceful surroundings with stunning lake views. The cottage features a cozy interior with a fireplace, perfect for romantic getaways or family vacations. Explore nearby hiking trails, go fishing, or simply unwind on the private dock. This retreat promises a rejuvenating experience in nature's embrace.",
                            FeaturesList = "[1,2]",
                            LandLordId = 2,
                            NumberOfGuests = 4,
                            PricePerDay = 110f,
                            Rooms = 2,
                            Subtitle = "Tranquil waterside retreat",
                            Title = "Rustic Cottage by the Lake",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Live in style in this sleek urban loft situated in the heart of downtown. Experience contemporary living with high ceilings, industrial-chic decor, and panoramic city views. The loft is fully equipped with state-of-the-art amenities and is ideal for professionals or urban explorers seeking convenience and luxury. Step outside to trendy cafes, art galleries, and nightlife hotspots for a vibrant city experience.",
                            FeaturesList = "[2,3]",
                            LandLordId = 3,
                            NumberOfGuests = 2,
                            PricePerDay = 180f,
                            Rooms = 1,
                            Subtitle = "Modern city living",
                            Title = "Urban Loft in Downtown",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Embrace tranquility at this secluded mountain retreat, surrounded by majestic peaks and lush forests. The cabin offers a cozy atmosphere with wood-panelled interiors, a crackling fireplace, and breathtaking mountain views from the deck. Hike scenic trails, spot wildlife, or simply relax in the hot tub under the starlit sky. This retreat is perfect for nature enthusiasts and those seeking a peaceful mountain escape.",
                            FeaturesList = "[1,5]",
                            LandLordId = 2,
                            NumberOfGuests = 6,
                            PricePerDay = 200f,
                            Rooms = 3,
                            Subtitle = "A sanctuary in the mountains",
                            Title = "Secluded Mountain Retreat",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Indulge in luxury at this beachfront villa boasting panoramic ocean views and direct beach access. The villa features spacious rooms, elegant decor, and a private pool overlooking the sea. Pamper yourself with in-villa spa treatments or dine al fresco on the terrace with sunset views. Explore pristine beaches, water sports, and local seafood cuisine for a luxurious coastal retreat.",
                            FeaturesList = "[2,4]",
                            LandLordId = 1,
                            NumberOfGuests = 8,
                            PricePerDay = 500f,
                            Rooms = 4,
                            Subtitle = "Exclusive oceanfront living",
                            Title = "Luxury Beachfront Villa",
                            Type = 5
                        },
                        new
                        {
                            Id = 9,
                            Description = "Step back in time at this historic manor house, offering grandeur and elegance amidst sprawling gardens and ancient architecture. The manor features opulent rooms, antique furnishings, and impeccable service for a luxurious stay. Stroll through manicured gardens, enjoy afternoon tea in the drawing room, or explore nearby historic landmarks. This estate promises a refined retreat steeped in history.",
                            FeaturesList = "[2,5]",
                            LandLordId = 3,
                            NumberOfGuests = 20,
                            PricePerDay = 1000f,
                            Rooms = 10,
                            Subtitle = "Elegant heritage accommodation",
                            Title = "Historic Manor House",
                            Type = 4
                        },
                        new
                        {
                            Id = 10,
                            Description = "Escape to this cozy ski chalet nestled in a picturesque alpine village. The chalet features timber interiors, a roaring fireplace, and stunning mountain views from the balcony. Ski-in, ski-out access makes it perfect for winter sports enthusiasts, while summer visitors can hike scenic trails or relax in the sauna. Enjoy après-ski in the village or unwind with hot chocolate by the fire.",
                            FeaturesList = "[2,3,4]",
                            LandLordId = 2,
                            NumberOfGuests = 6,
                            PricePerDay = 250f,
                            Rooms = 3,
                            Subtitle = "Winter wonderland getaway",
                            Title = "Cozy Ski Chalet",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Experience country charm at this quaint bed and breakfast nestled in rolling hills. The B&B offers cozy rooms with floral decor, homemade breakfasts, and a warm, welcoming atmosphere. Explore nearby vineyards, go horseback riding, or simply relax in the garden with a book. This retreat is ideal for couples seeking a peaceful rural escape.",
                            FeaturesList = "[5]",
                            LandLordId = 1,
                            NumberOfGuests = 10,
                            PricePerDay = 150f,
                            Rooms = 5,
                            Subtitle = "Charming bed and breakfast",
                            Title = "Quaint Countryside B&B",
                            Type = 5
                        },
                        new
                        {
                            Id = 12,
                            Description = "Enjoy unparalleled luxury in this lakeview penthouse suite boasting floor-to-ceiling windows and a private terrace overlooking the water. The suite features contemporary design, high-end amenities, and exclusive access to a rooftop pool and spa. Indulge in gourmet dining, yacht cruises, or lakeside walks for a sophisticated lakeside retreat.",
                            FeaturesList = "[2,3,4]",
                            LandLordId = 3,
                            NumberOfGuests = 4,
                            PricePerDay = 350f,
                            Rooms = 2,
                            Subtitle = "Luxury lakeside living",
                            Title = "Lakeview Penthouse Suite",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Immerse yourself in nature at this eco-friendly treehouse retreat hidden deep in the forest. The treehouse offers a unique stay with sustainable design, panoramic forest views, and tranquil surroundings. Disconnect from technology, hike through ancient woods, or stargaze from the treehouse deck. This retreat is perfect for eco-conscious travelers seeking a back-to-nature experience.",
                            FeaturesList = "[1]",
                            LandLordId = 2,
                            NumberOfGuests = 2,
                            PricePerDay = 80f,
                            Rooms = 1,
                            Subtitle = "Off-grid wilderness escape",
                            Title = "Eco-Friendly Treehouse",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Experience modern living in this sleek city studio located in a bustling downtown district. The studio features minimalist decor, a compact kitchenette, and access to a rooftop garden with city skyline views. Explore nearby cafes, shops, and cultural attractions or retreat to your stylish urban oasis after a day of city exploration.",
                            FeaturesList = "[2]",
                            LandLordId = 1,
                            NumberOfGuests = 2,
                            PricePerDay = 100f,
                            Rooms = 1,
                            Subtitle = "Convenient urban living",
                            Title = "Modern City Studio",
                            Type = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Escape to this charming log cabin nestled on the shores of a tranquil lake. The cabin features rustic wood interiors, a stone fireplace, and a private dock for fishing and boating. Enjoy serene lake views from the porch swing or explore nearby hiking trails and wildlife spotting opportunities. This cabin promises a cozy retreat in nature's embrace.",
                            FeaturesList = "[2,1]",
                            LandLordId = 3,
                            NumberOfGuests = 4,
                            PricePerDay = 150f,
                            Rooms = 2,
                            Subtitle = "Rustic lakeside retreat",
                            Title = "Lakeside Log Cabin",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostumerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CostumerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostumerId = 1,
                            Discount = 10f,
                            EndDate = new DateTime(2024, 6, 27, 23, 0, 27, 424, DateTimeKind.Local).AddTicks(9544),
                            LocationId = 1,
                            StartDate = new DateTime(2024, 6, 24, 23, 0, 27, 424, DateTimeKind.Local).AddTicks(9504)
                        },
                        new
                        {
                            Id = 2,
                            CostumerId = 2,
                            Discount = 5f,
                            EndDate = new DateTime(2024, 6, 29, 23, 0, 27, 424, DateTimeKind.Local).AddTicks(9551),
                            LocationId = 2,
                            StartDate = new DateTime(2024, 6, 24, 23, 0, 27, 424, DateTimeKind.Local).AddTicks(9549)
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Image", b =>
                {
                    b.HasOne("Adambnb.Models.LandLord", "LandLord")
                        .WithOne("Avatar")
                        .HasForeignKey("Adambnb.Models.Image", "LandLordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adambnb.Models.Location", "Location")
                        .WithMany("Images")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LandLord");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Adambnb.Models.Location", b =>
                {
                    b.HasOne("Adambnb.Models.LandLord", "LandLord")
                        .WithMany("Locations")
                        .HasForeignKey("LandLordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandLord");
                });

            modelBuilder.Entity("Adambnb.Models.Reservation", b =>
                {
                    b.HasOne("Adambnb.Models.Costumer", "Costumer")
                        .WithMany("Reservations")
                        .HasForeignKey("CostumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adambnb.Models.Location", "Location")
                        .WithMany("Reservations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costumer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Adambnb.Models.Costumer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Adambnb.Models.LandLord", b =>
                {
                    b.Navigation("Avatar")
                        .IsRequired();

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Adambnb.Models.Location", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
