// <auto-generated />
using System;
using Adambnb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adambnb.Migrations
{
    [DbContext(typeof(AdambnbContext))]
    partial class AdambnbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adambnb.Models.Costumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Costumers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int>("LandLordId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandLordId")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCover = true,
                            LandLordId = 1,
                            LocationId = 1,
                            Url = "image1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsCover = true,
                            LandLordId = 2,
                            LocationId = 2,
                            Url = "image2.jpg"
                        });
                });

            modelBuilder.Entity("Adambnb.Models.LandLord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LandLords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            FirstName = "Landlord1",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 40,
                            FirstName = "Landlord2",
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LandLordId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandLordId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "De camping ligt verscholen achter de boerderij in de polder. Geniet van de rust en ruimte op De Boerenhoeve, waar de natuur je omringt en de frisse lucht je verwelkomt. Onze comfortabele appartementen bieden een thuis weg van huis, met moderne voorzieningen en een sfeervolle inrichting. Ontspan op het terras en bewonder het prachtige uitzicht op de omringende weilanden. Of verken de nabijgelegen wandel- en fietspaden voor een onvergetelijke ervaring in de natuur. We heten je van harte welkom op De Boerenhoeve!",
                            FeaturesList = "[2,3]",
                            LandLordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 100f,
                            Rooms = 2,
                            Subtitle = "Lekker veel ruimte",
                            Title = "De Boerenhoeve",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ervaar de ultieme vakantie aan de kust in ons Zeezicht Appartement. Geniet van adembenemende uitzichten op de zee vanuit je ruime en comfortabele accommodatie. Ontspan op het balkon en luister naar het rustgevende geluid van de golven. Het appartement is smaakvol ingericht en voorzien van moderne voorzieningen. Verken de nabijgelegen stranden, restaurants en bezienswaardigheden voor een onvergetelijke vakantie aan zee.",
                            FeaturesList = "[2,3,4]",
                            LandLordId = 2,
                            NumberOfGuests = 6,
                            PricePerDay = 150f,
                            Rooms = 3,
                            Subtitle = "Prachtig uitzicht op de zee",
                            Title = "Zeezicht Appartement",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ontsnap aan de drukte en omarm de natuur in ons Groene Oase Chalet. Dit charmante chalet is omgeven door weelderig groen en biedt een rustige toevluchtsoord voor natuurliefhebbers. Het chalet is voorzien van alle gemakken en beschikt over een eigen tuin waar je kunt genieten van de flora en fauna. Verken de wandelpaden, observeer vogels en kom helemaal tot rust in deze groene oase.",
                            FeaturesList = "[1,5]",
                            LandLordId = 1,
                            NumberOfGuests = 2,
                            PricePerDay = 120f,
                            Rooms = 1,
                            Subtitle = "Omgeven door natuur",
                            Title = "Groene Oase Chalet",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Verblijf in stijl in ons Historisch Stadsappartement, gelegen in het hart van de oude stad. Het appartement combineert moderne luxe met historische charme en biedt een unieke ervaring. Wandel door smalle steegjes, ontdek historische bezienswaardigheden en proef lokale gerechten in de nabijgelegen restaurants. Het appartement is smaakvol ingericht en voorzien van alle moderne gemakken voor een comfortabel en cultureel verblijf.",
                            FeaturesList = "[2,3]",
                            LandLordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 130f,
                            Rooms = 2,
                            Subtitle = "Verken de oude stad",
                            Title = "Historisch Stadsappartement",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostumerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CostumerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostumerId = 1,
                            Discount = 10f,
                            EndDate = new DateTime(2024, 3, 2, 12, 0, 26, 363, DateTimeKind.Local).AddTicks(7646),
                            LocationId = 1,
                            StartDate = new DateTime(2024, 2, 28, 12, 0, 26, 363, DateTimeKind.Local).AddTicks(7584)
                        },
                        new
                        {
                            Id = 2,
                            CostumerId = 2,
                            Discount = 5f,
                            EndDate = new DateTime(2024, 3, 4, 12, 0, 26, 363, DateTimeKind.Local).AddTicks(7662),
                            LocationId = 2,
                            StartDate = new DateTime(2024, 2, 28, 12, 0, 26, 363, DateTimeKind.Local).AddTicks(7660)
                        });
                });

            modelBuilder.Entity("Adambnb.Models.Image", b =>
                {
                    b.HasOne("Adambnb.Models.LandLord", "LandLord")
                        .WithOne("Avatar")
                        .HasForeignKey("Adambnb.Models.Image", "LandLordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adambnb.Models.Location", "Location")
                        .WithMany("Images")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LandLord");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Adambnb.Models.Location", b =>
                {
                    b.HasOne("Adambnb.Models.LandLord", "LandLord")
                        .WithMany("Locations")
                        .HasForeignKey("LandLordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandLord");
                });

            modelBuilder.Entity("Adambnb.Models.Reservation", b =>
                {
                    b.HasOne("Adambnb.Models.Costumer", "Costumer")
                        .WithMany("Reservations")
                        .HasForeignKey("CostumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adambnb.Models.Location", "Location")
                        .WithMany("Reservations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costumer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Adambnb.Models.Costumer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Adambnb.Models.LandLord", b =>
                {
                    b.Navigation("Avatar")
                        .IsRequired();

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Adambnb.Models.Location", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
